name: automerge
on:
  schedule:
    - cron: "0 21 * * *"

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests (automerge-action)
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_FOR_CODING_TEST_STUDY }}
          MERGE_LABELS: "!❔Unresolved"
          MERGE_METHOD: "rebase"
          MERGE_FORKS: "true"
          MERGE_DELETE_BRANCH: "true"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_REQUIRED_APPROVALS: 2
          UPDATE_LABELS: "automerge"
